### ISSUE TITLE
int8_t Vs uint8_t

### ISSUE THREAD

**Issue by lovrosverko** [PozitronSSER/WasteManagement#12]
Koja je razlika između int8_t i uint8_t?

https://github.com/PozitronSSER/WasteManagement/blob/166e7497b55b2ae9dc12601613f4c794201bbf9f/kantaZaSmece/kantaZaSmece/kantaZaSmece.ino#L226

**Comment by patrik-horvat1** [comment]
int8_t koristi drugi komplement za negativne brojeve, i ne koristi padding bit

**Comment by lovrosverko** [comment]
A sta je komplement  i padding bit?

Dana 18. sij 2018. 10:54 AM osoba "Patrik Horvat" <notifications@github.com>
napisala je:

**Comment by patrik-horvat1** [comment]
Bit padding is the addition of one or more extra bits to a storage unit to make it conform to a standard size.
