### ISSUE TITLE
trebaju li ovi bool-ovi?

### ISSUE THREAD

**Issue by lovrosverko** [PozitronSSER/WasteManagement#3]
https://github.com/PozitronSSER/WasteManagement/blob/06af1a48acea0cf81b67fcdbe6dbf24c24b37b46/kantaZaSmece/kantaZaSmece/kantaZaSmece.ino#L48

**Comment by BigWillyHaver69** [comment]
A istina, nisam skuzio da se ne koriste nigdje vise.
