### ISSUE TITLE
maknite ovu liniju, zbog toga ne radi GPS

### ISSUE THREAD

**Issue by lovrosverko** [PozitronSSER/WasteManagement#5]
https://github.com/PozitronSSER/WasteManagement/blob/06af1a48acea0cf81b67fcdbe6dbf24c24b37b46/kantaZaSmece/kantaZaSmece/kantaZaSmece.ino#L156

**Comment by BigWillyHaver69** [comment]
Samo specificno tu liniju da maknem

**Comment by BigWillyHaver69** [comment]
Maknuo sam taj if tako da sad bi valjda trebalo bit ok
