### ISSUE TITLE
maknite ovo, ali provjerite da li se ta metoda poziva negdje u kodu prije toga.

### ISSUE THREAD

**Issue by lovrosverko** [PozitronSSER/WasteManagement#7]
https://github.com/PozitronSSER/WasteManagement/blob/06af1a48acea0cf81b67fcdbe6dbf24c24b37b46/kantaZaSmece/kantaZaSmece/kantaZaSmece.ino#L353

Što zapravo radi ova metoda?

**Comment by BigWillyHaver69** [comment]
Poziva se u kodu, 2 puta kod ispisa koordinata GPS - a

**Comment by lovrosverko** [comment]
Dobro. A šta radi ta metoda?

**Comment by BigWillyHaver69** [comment]
Pretvara broj u float

**Comment by lovrosverko** [comment]
Ne.

Dana 18. sij 2018. 10:33 AM osoba "Vanja Ljubobratovic" <
notifications@github.com> napisala je:
